# Default values for uportal-demo-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: markmclaren/uportal-demo-k8s
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  # type: ClusterIP
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  #paths: ['/']
  #hosts:
  #  - localhost
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Just start Tomcat
#startupCommand: "echo 'Starting up...' && /home/gradle/.gradle/tomcat/bin/catalina.sh start && tail -f /dev/null"

# Run Gradle dataInit and start Tomcat (works in Docker desktop)
startupCommand: "echo 'Starting up...' && env && gradle --no-daemon --info dataInit && /home/gradle/.gradle/tomcat/bin/catalina.sh start && tail -f /dev/null"

##
## MariaDB chart configuration
##
## https://github.com/helm/charts/blob/master/stable/mariadb/values.yaml
##
mariadb:
  ## Disable MariaDB replication
  replication:
    enabled: false

  ## Create a database and a database user
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-user-on-first-run
  ##
  db:
    name: uportal
    user: uportal
    ## If the password is not specified, mariadb will generates a random password
    ##
    password: uportal

  ## MariaDB admin password
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  # rootUser:
  #   password:

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  master:
    persistence:
      enabled: true
      ## mariadb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 8Gi

    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=utf8mb4
      collation-server=utf8mb4_unicode_520_ci
      #
      default-storage-engine=INNODB
      lower_case_table_names=1
      innodb-large-prefix=1
      innodb_file_format=Barracuda
      innodb_file_format_check=1
      innodb_file_format_max=Barracuda
      innodb_file_per_table=1
      innodb_strict_mode=ON

      #innodb_buffer_pool_size=2G
      #innodb_data_home_dir=/var/lib/mysql/
      #innodb_data_file_path=ibdata1:100M:autoextend
      #innodb_flush_log_at_trx_commit=1
      #innodb_log_file_size=256M
      #innodb_log_buffer_size=64M      

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=utf8mb4

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

#  initdbScripts:
#    init_db.sql: |
#      CREATE USER 'uportal'@'localhost' IDENTIFIED BY 'uportal';
#      create database uportal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
#      GRANT ALL PRIVILEGES ON uportal.* TO 'uportal'@'localhost';

