# Default values for uportal-demo-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: markmclaren/uportal-demo-k8s
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  # type: ClusterIP
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /uPortal
    # kubernetes.io/tls-acme: "true"
  paths: ['/']
  hosts: 
    - localhost
  tls: []  
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {} 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
  #  cpu: 2000m
  #  memory: 12288Mi
  #requests:
  #  cpu: 500m
  #  memory: 8096Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Just start Tomcat
#startupCommand: "echo 'Starting up...' && /home/gradle/.gradle/tomcat/bin/catalina.sh start && tail -f /dev/null"

# Run Gradle dataInit and start Tomcat (works in Docker desktop)
startupCommand: "echo 'Starting up...' && env && gradle --no-daemon --info dataInit && /home/gradle/.gradle/tomcat/bin/catalina.sh start && tail -f /dev/null"

##
## MariaDB chart configuration
##
## https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml
##
mariadb:
  ## Disable MariaDB replication
  replication:
    enabled: false

  ## MariaDB admin credentials
  ##
  rootUser:
    ## MariaDB admin password
    ## ref: https://github.com/bitnami/bitnami-docker-mariadb#setting-the-root-password-on-first-run
    ##
    password: ""
    ## Option to force users to specify a password. That is required for 'helm upgrade' to work properly.
    ## If it is not force, a random password will be generated.
    ##
    forcePassword: false
    ## Mount admin password as a file instead of using an environment variable
    ##
    injectSecretsAsVolume: false  

  ## Create a database and a database user
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-user-on-first-run
  ##
  db:
    name: uportal
    user: uportal
    ## If the password is not specified, mariadb will generates a random password
    ##
    password: uportal
    ## Option to force users to specify a password. That is required for 'helm upgrade' to work properly.
    ## If it is not force, a random password will be generated.
    ##
    forcePassword: false
    ## Mount user password as a file instead of using an environment variable
    ##
    injectSecretsAsVolume: false

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  master:
    persistence:
      enabled: true
      ## mariadb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 8Gi

    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=256M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=utf8mb4
      collation-server=utf8mb4_unicode_520_ci
      # In MariadDB 10.3.22. many of the Barracuda 
      # settings are default
      lower_case_table_names=1
      innodb_file_per_table=ON
      innodb_strict_mode=ON  

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=utf8mb4
      plugin_dir=/opt/bitnami/mariadb/plugin      

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

#  initdbScripts:
#    init_db.sql: |
#      CREATE USER 'uportal'@'localhost' IDENTIFIED BY 'uportal';
#      create database uportal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
#      GRANT ALL PRIVILEGES ON uportal.* TO 'uportal'@'localhost';

